name: bide_et_musique
description: Ã‰couter et consulter la web radio 'Bide et Musique'

version: 3.3.4+43

environment:
  sdk: '>=2.7.0'

dependencies:
  flutter:
    sdk: flutter
  audio_service: ^0.14.0
  cached_network_image: ^2.3.1
  diacritic: ^0.1.1
  flutter_html: ^1.0.2
  html: ^0.14.0+3
  http: ^0.12.2
  just_audio: ^0.4.0
  package_info: ^0.4.3
  page_indicator: ^0.3.0
  share: ^0.6.5
  shared_preferences: ^0.5.10
  uni_links: ^0.4.0
  url_launcher: ^5.5.1
  xml: ^4.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/bandeau.png
    - assets/bm_logo_white.png
    - assets/vinyl-default.jpg
    - android/app/src/main/res/mipmap-mdpi/ic_launcher.png