name: bide_et_musique
description: Ã‰couter et consulter la web radio 'Bide et Musique'

version: 3.3.9+48

environment:
  sdk: '>=2.7.0'

dependencies:
  flutter:
    sdk: flutter
  audio_service: ^0.17.0
  cached_network_image: ^3.0.0
  diacritic: ^0.1.3
  flutter_html: ^2.0.0-nullsafety.0
  html: ^0.15.0
  http: ^0.13.1
  just_audio: ^0.7.2
  package_info: ^2.0.0
  page_indicator: ^0.4.1
  share: ^2.0.1
  shared_preferences: ^2.0.5
  uni_links: ^0.4.0
  url_launcher: ^6.0.2
  xml: ^5.0.2
  flutter_launcher_icons: ^0.9.0
  flutter_statusbarcolor: ^0.2.3

flutter_icons:
  android: false
  ios: true
  image_path: "assets/bm_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/bandeau.png
    - assets/bm_logo_white.png
    - assets/vinyl-default.jpg
    - android/app/src/main/res/mipmap-mdpi/ic_launcher.png