name: bide_et_musique
description: Ã‰couter et consulter la web radio 'Bide et Musique'

version: 3.3.10+49

environment:
  sdk: '>=2.11.0'

dependencies:
  flutter:
    sdk: flutter
  audio_service: ^0.17.1
  cached_network_image: ^3.1.0
  diacritic: ^0.1.3
  flutter_html: ^2.1.0
  html: ^0.15.0
  http: ^0.13.1
  just_audio: 0.8.0
  package_info: ^2.0.2
  page_indicator: ^0.4.1
  share: ^2.0.4
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.3
  xml: ^5.1.2
  flutter_launcher_icons: ^0.9.0
  flutter_statusbarcolor_ns: ^0.3.0-nullsafety

flutter_icons:
  android: false
  ios: true
  image_path: "assets/bm_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/bandeau.png
    - assets/bm_logo_white.png
    - assets/vinyl-default.jpg
    - android/app/src/main/res/mipmap-mdpi/ic_launcher.png